domain: []
external_id_method: row_get_id
external_id_nomenclature: product_pricelist_%s
fields:
  code:
    from:
      name: code
      type: char
    map_method: magic_map
    to:
      name: code
      type: char
model_from: product.pricelist
model_to: product.pricelist
no_match_fields: []
